# Generated by Django 4.1.5 on 2023-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_addexpensemodel_expense_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("travel", "Travel"),
                            ("bills", "Bills"),
                            ("clothes", "Clothes"),
                            ("groceries", "Groceries"),
                            ("extra", "Extra"),
                        ],
                        default="extra",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
