# Generated by Django 4.1.5 on 2023-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_categorylookup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addexpensemodel",
            name="expense_added",
            field=models.DateField(),
        ),
    ]
